import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  flexCenter: {
    // flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
});

export const containerShadow = StyleSheet.create({
  containerShadow: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 2,
  },
});

export const stylesIndex = StyleSheet.create({
  container: {
    alignItems: "center",
    width: "100%",
    minHeight: "100%",
    backgroundColor: "#2D3E40",
    paddingBottom: 30,
    paddingTop: 10,
  },
  header: {
    width: "100%",

    // borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    // paddingVertical: 18,
    paddingHorizontal: 20,
    marginTop: 10,
    marginBottom: 20,
    // ...containerShadow.containerShadow,
  },
  headerWeekday: {
    color: "#FFFF",
    fontSize: 22,
    fontWeight: "bold",
  },
  headerDate: {
    color: "#FFFF",
    fontWeight: "normal",
    fontSize: 18,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  dailyProgressContainer: {
    justifyContent: "center",
    alignItems: "center",
    width: "90%",
    padding: 18,
    backgroundColor: "#fff",
    borderRadius: 16,
    marginVertical: 20,
    ...containerShadow.containerShadow,
  },
  calorieProgressContainer: {
    width: "90%",
    height: "auto",
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 16,
    paddingVertical: 20,
  },
  calorieStatusContainer: {
    justifyContent: "center",
    alignItems: "center",
  },
  sectionTitle: {
    color: "#D4AA7D",
    fontSize: 20,
    fontWeight: "bold",
    // marginBottom: 10,
    marginTop: 10,
    alignSelf: "flex-start",
    marginLeft: "auto",
    marginRight: "auto",
  },
  historyContainer: {
    width: "90%",
    // backgroundColor: "#3e4e50",
    borderRadius: 16,
    padding: 16,
    // marginTop: 10,
    marginBottom: 30,
    // ...containerShadow.containerShadow,
  },
  emptyHistoryText: {
    color: "#b0b0b0",
    textAlign: "center",
    fontSize: 16,
    paddingVertical: 20,
  },
});

// export const stylesDailyGoal = StyleSheet.create({
//   container: {
//     justifyContent: "center",
//     alignItems: "center",
//     width: "100%",
//     minHeight: "100%",
//     backgroundColor: "#B2C9AD",
//   },
//   inputContainer: {
//     width: "80%",
//     // minHeight: "100%",
//   },
//   containerShadow: {
//     shadowColor: "#000",
//     shadowOffset: { width: 0, height: 2 },
//     shadowOpacity: 0.25,
//     shadowRadius: 3.84,
//     elevation: 2,
//   },
//   dailyProgressContainer: {
//     justifyContent: "center",
//     alignItems: "center",
//     width: 300,
//     padding: 20,
//     marginTop: 10,
//     backgroundColor: "#91AC8F",
//     borderRadius: 15,
//     marginVertical: 20,
//     shadowColor: "#000",
//     shadowOffset: { width: 0, height: 2 },
//     shadowOpacity: 0.25,
//     shadowRadius: 3.84,
//     elevation: 2,
//   },
//   title: {
//     position: "absolute",
//     top: 70,

//     textAlign: "center",
//     textAlignVertical: "center",

//     width: "60%",
//     height: 50,

//     borderRadius: 10,

//     fontSize: 20,
//     fontWeight: "bold",

//     color: "white",
//     backgroundColor: "#91AC8F",
//   },
//   label: {
//     fontSize: 16,
//     marginBottom: 5,
//     fontWeight: "bold",
//     color: "white",
//   },
//   input: {
//     width: "100%",
//     padding: 10,
//     marginBottom: 15,
//     backgroundColor: "#fff",
//     borderRadius: 10,
//     borderWidth: 1,
//     borderColor: "#ccc",
//   },
//   button: {
//     width: "100%",
//     padding: 15,
//     backgroundColor: "#91AC8F",
//     borderRadius: 10,
//     alignItems: "center",
//   },
//   buttonText: {
//     color: "#fff",
//     fontSize: 16,
//     fontWeight: "bold",
//   },
// });

export const stylesDailyGoal = StyleSheet.create({
  container: {
    // alignItems: "center",
    width: "100%",
    minHeight: "100%",
    backgroundColor: "#2D3E40",
    paddingTop: 45,
    paddingBottom: 20,
  },
  inputContainer: {
    width: "90%",
    marginHorizontal: "auto",
    // backgroundColor: "#5D7073",
    borderRadius: 7,
    padding: 20,
    marginTop: 10,
    // ...containerShadow.containerShadow,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "white",
    // backgroundColor: "#D4AA7D",
    width: "90%",
    // textAlign: "center",
    // paddingVertical: 15,
    marginLeft: 20,
    borderRadius: 7,
    // marginBottom: 10,
    overflow: "hidden",
    // ...containerShadow.containerShadow,
  },
  label: {
    fontSize: 16,
    marginBottom: 5,
    fontWeight: "bold",
    color: "#D4AA7D",
    marginTop: 10,
    maxWidth: "100%",
  },
  input: {
    width: "100%",
    padding: 12,
    marginBottom: 10,
    // backgroundColor: "#8FA3A6",
    backgroundColor: "#fff",
    borderTopRightRadius: 5,
    borderTopLeftRadius: 5,
    borderBottomWidth: 1,
    borderColor: "#D4AA7D",
    fontSize: 16,
    color: "#2D3E40",
    ...containerShadow.containerShadow,
  },
  button: {
    width: "100%",
    padding: 15,
    backgroundColor: "#fff",
    // backgroundColor: "#D4AA7D",
    borderRadius: 5,
    alignItems: "center",
    marginTop: 20,
    ...containerShadow.containerShadow,
  },
  buttonText: {
    color: "#D4AA7D",
    fontSize: 18,
    fontWeight: "bold",
  },
});
